using System.Text.Json.Serialization;
using ElavonPaymentsNet.Models.Public;

namespace ElavonPaymentsNet.Models.Public.Responses;

/// <summary>Response returned after requesting an Apple Pay merchant session.</summary>
public sealed class ApplePaySessionResponse
{
    /// <summary>Result of the session request, e.g. "Ok", "Invalid", "Error".</summary>
    public string? Status { get; init; }

    /// <summary>
    /// Strongly typed view of <see cref="Status"/>.
    /// Unknown or newly introduced API statuses map to <see cref="TransactionStatusKind.Unknown"/>.
    /// </summary>
    [JsonIgnore]
    public TransactionStatusKind StatusKind => TransactionStatus.ParseKind(Status);

    /// <summary>Code related to the status of the request.</summary>
    public string? StatusCode { get; init; }

    /// <summary>A detailed reason for the status of the request.</summary>
    public string? StatusDetail { get; init; }

    /// <summary>The signature creation time in Unix epoch milliseconds.</summary>
    public long? EpochTimeStamp { get; init; }

    /// <summary>The session expiry time in Unix epoch milliseconds.</summary>
    public long? ExpiresAt { get; init; }

    /// <summary>The merchant session identifier to be passed to <c>completeMerchantValidation</c> in the browser.</summary>
    public string? MerchantSessionIdentifier { get; init; }

    /// <summary>A one-time nonce value generated by Apple's servers.</summary>
    public string? Nonce { get; init; }

    /// <summary>Your Apple Pay merchant identifier.</summary>
    public string? MerchantIdentifier { get; init; }

    /// <summary>The domain registered with Apple Pay.</summary>
    public string? DomainName { get; init; }

    /// <summary>The display name associated with your vendor account.</summary>
    public string? DisplayName { get; init; }

    /// <summary>A hash of the public key used to sign the interactions.</summary>
    public string? Signature { get; init; }

    /// <summary>
    /// The session validation token. This must be presented with the Apple Pay transaction request exactly as returned here.
    /// </summary>
    public string? SessionValidationToken { get; init; }
}
